# Generated by Django 5.1.1 on 2024-09-04 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZidUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("user_uuid", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ZidUserStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.CharField(max_length=50)),
                ("store_uuid", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zid_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="oauth.ziduser"
                    ),
                ),
            ],
        ),
    ]
