# Generated by Django 5.1.1 on 2024-09-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0002_ziduser_ziduserstore"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TokenData",
        ),
        migrations.AddField(
            model_name="ziduser",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ziduser",
            name="authorization_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ziduser",
            name="expires_in",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ziduser",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ziduser",
            name="token_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ziduser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="ziduser",
            name="mobile",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ziduser",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ziduser",
            name="user_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ziduser",
            name="user_uuid",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ziduserstore",
            name="store_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
